# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This project aims to deal with modules related to the management
    of barcode in a generic way.
repo_name: Odoo Stock Logistic Barcode
repo_slug: stock-logistics-barcode
repo_website: https://github.com/OCA/stock-logistics-barcode
travis_apt_packages: []
travis_apt_sources: []

