[project]
name = "odoo-addons-oca-stock-logistics-barcode"
version = "19.0.20260830.0"
dependencies = [
    "odoo-addon-barcodes_generator_abstract==19.0.*",
    "odoo-addon-barcodes_generator_product==19.0.*",
    "odoo-addon-product_multi_barcode==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
